name: test workflow

run-name: Run by @${{ github.actor }}

on:
  push:
    tags: 
        - "v*"

env:
  REGISTRY: hub.oepkgs.net
  IMAGE_NAME: wangliu/test2

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Generate Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value={{tag}}
          type=raw,value=release,enable=${{ env.GITHUB_REF_TYPE == 'tag' }}

    
    - name: check tag
      env:
        TAGS: ${{ steps.meta.outputs.tags }}
        TYPE: ${{ env.GITHUB_REF_TYPE }}
      run: |
        echo ${TAGS}
        echo ${TYPE}
